language: go
sudo: required
services:
  - docker

go:
  - "1.10"
  #- "1.9"
  #- "1.8"

env:
  global:
  - WATCHER_VERSION=0.2.4

matrix:
  fast_finish: true

script: |
  GO_VERSION=$(go version | awk 'print $3')
  docker build -f Dockerfiles/Dockerfile."$GO_VERSION" -t canthefason/go-watcher:$WATCHER_VERSION-$GO_VERSION .
  docker push canthefason/go-watcher:$WATCHER_VERSION-$GO_VERSION

