language: go
sudo: required
services:
  - docker

go:
  - GO_VERSION=1.10
  - GO_VERSION=1.9
  - GO_VERSION=1.8

env:
  global:
  - WATCHER_VERSION=0.2.4

matrix:
  fast_finish: true

script: |
  docker build -f Dockerfiles/Dockerfile.go$GO_VERSION -t canthefason/go-watcher:$WATCHER_VERSION-$GO_VERSION .
  docker push canthefason/go-watcher:$WATCHER_VERSION-$GO_VERSION

