language: go
sudo: required
services:
  - docker

go:
  - 1.10
  - 1.9
  - 1.8

env:
  global:
  - WATCHER_VERSION=0.2.4

matrix:
  fast_finish: true

script: |
  docker build -f Dockerfiles/Dockerfile.$(go version | awk '{print $3}') -t canthefason/go-watcher:$WATCHER_VERSION-$(go version | awk '{print $3}') .
  docker push canthefason/go-watcher:$WATCHER_VERSION-$GO_VERSION

